# Generated by Django 5.1.3 on 2024-11-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('color', models.CharField()),
                ('scent', models.CharField(choices=[('NONE', 'No Smell'), ('SWEET', 'Sweet'), ('STRONG', 'Strong'), ('EARTHY', 'Earthy')], default='NONE')),
            ],
        ),
    ]
