# Generated by Django 5.1.3 on 2024-11-13 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.CharField(choices=[('L', 'Light'), ('M', 'Moderate'), ('H', 'Heavy')], default='L')),
                ('flowers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.flowers')),
            ],
        ),
    ]
